name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN:  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 # Needed to get PR information, if any
          SONAR_TOKEN: 00ab29f19d1d545ae43568efb0377cb33dfb24ee
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test